### ISSUE TITLE
Реализация функционала добавления типов контента

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#10]
**Конечный результат:**

Реализовать пользователю с ролью "admin" возможность добавления типов контента.

**План решения:**

В личном кабинете добавить кнопку "Добавить тип контента".

Написать функционал создания администратором типов контента и внесения в БД, для последующего применения при внесении Post. Привязать функционал к кнопке "Добавить тип контента".

**Мотивация:**

По тех. заданию вносимый контент должен быть разделен по типам (Пример: Текст,Аудио, Видео)

**Критерии приемки:**

У администратора в личном кабинете при нажатии на кнопку "Добавить тип контента" должно открыться окно с формой для внесения нового типа, где будет одно поле string "Укажите тип" и кнопка "Добавить". После добавления, данный тип должен быть записан в БД, для дальнейшего использования при внесении контента.

**Планируемое время работы:**
1 час

**Comment by GalinaDugina** [comment]
При создании поста добавляется тип, но записи в бд нет, поле неверно подписано
