### ISSUE TITLE
Откорректировать по замечаниям Книга

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#100]
**Конечный результат:**

При создании книги, присутствует возможность добавить БП, ключевые слова и возможность связать русскую версию книги с английской.

**План решения:**

Добавить в создание книг, возможность добавления ключевых слов, связь с БП и между русской и английской версией книг.
Предусмотреть связывающую таблицу для связи между книгами и БП, и книгами на разных языках.

**Мотивация:**

Заказчику необходимо связывать книги, добавлять к книгам БП, а также добавлять ключевые слова.

**Критерии приемки:**

При создании книги, присутствуют поля для выбора БП, для связи между книгами и поле для добавления ключевых слов.

**Планируемое время работы:**

**Comment by MuhtarLotov** [comment]
потраченное время 4 ч было добавлено кнопка перехода между связанными книгами в просмотре книги
