### ISSUE TITLE
Откорректировать Источник

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#101]
**Конечный результат:**

Добавить в источник поля для ввода ключевых слов, для выбора нескольких БП, а также поле для выбора изображения обложки источника. Изменить логику создания для папки хранения, загруженных файлов. Переименовывать файлы при загрузке

**План решения:**

Добавить в представление поля для ввода ключевых слов, для выбора нескольких БП, а также поле для выбора изображения обложки.
Поменять модель источника. 
Добавить модель связи между источником и БП.
Предусмотреть, чтобы поля могли принимать Null значения Сделать миграции. Добавить обработку в контроллер
Изменить логику создания  папки для хранения файлов, чтобы все не писалось в папку "0": для этого организовать запись файла после создания записи в БД
При записывании файла сделать логику по переименованию файлов перед сохранение
Сделать проверку на расширение файла, который сохраняется

**Мотивация:**

Заказчику необходимы данные поля для связи между сущностями, и для выбора обложки источника

**Критерии приемки:**

При создании источника в форме доступны поля для выбора нескольких БП, внесения ключевых слов, а также для загрузки обложки.

**Планируемое время работы:**
6 часов

**Comment by AlexeyGoikolov** [comment]
Затраченное время 7 часов. Возникли трудности с достоверностью проверки загружаемых файлов.
