### ISSUE TITLE
Реализация поиска 

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#104]
**Конечный результат:**
На стороне сотрудника появляется поле для поиска. 
Вводим слово или фразу и попадаем на страницу с результатом поиска, разделенного по сущностям в которых искали

**План решения:**
1. В LayoutEmployee для пользователя добавить окошко для поиска, куда можно вводить поисковой запрос.
2.Добавить в модели Источник и Книга поля с Ключевыми словами, по которым реализовать поиск через Базу данных 
3. В контроллере account добавить метод для поиска
для поиска использовать 
 Like
List<User> user = new List<User>(_db.Users.Where(u => EF.Functions.Like(u.UserName, a) ||
                                                                      EF.Functions.Like(u.Email, a) ||
                                                                      EF.Functions.Like(u.Name, a) ||
                                                                      EF.Functions.Like(u.Description, a)));
здесь "а" это строка запроса, которую надо привести одинаковой высоте букв и убрать пробелы с краев
Поиск производить среди Источников, Книг по описанию, названию и ключевым словам. Среди Задач, Шагов, Термины, Ситуации по описанию и названию
4. Создать представление для отображения результатов поиска в виде ссылок
5. Результаты поиска выводить на странице шаблона Minovate 

**Мотивация:**
Сотруднику необходим поиск по всем данным  в БД

**Критерии приемки:**
Если Я вхожу в программу под логином пользователя
То в верхнем меню вижу строку поиска
Если в нее ввести поисковаой запрос
То попадаешь на страницу с результатом поиска
  результаты разделены в соответствии с сущностями по которым искали
Если надо продолжить поиск
То на странице результатов поиска есть строка для ввода следующего запроса

**Планируемое время работы:**
4.2 часа

**Comment by GalinaDugina** [comment]
потрачено 4 часа 20 минут
