### ISSUE TITLE
Настроить  страницу 404 и подключить обращение к ней

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#106]
***План решения:****
Убрать ManyRedirect и подключить стандартную страницу отображения ошибок
Поменять в файле launchSettings  в "ASPNETCORE_ENVIRONMENT" данные с development на Production для вывода ошибок, а не StackTrace.

**Мотивация:**
При воникновении ошибок, нужна страница об ошибке с указанием ее названия

**Планируемое время:** 
1,5 часа

**Comment by AlexeyGoikolov** [comment]
Затрачено 1,5 часа
