### ISSUE TITLE
Реализовать формирование ссылки на скачанный файл в виде http:////

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#108]
*План решения:**
Просмотреть код, найти в чем ошибка

**Мотивация:**
Чтобы просматривать файлы используя google docs , надо реализовать формирование ссылки на закаченный файл .

**Планируемое время:** 

30 минут

**Comment by AlexeyGoikolov** [comment]
Затрачено 30 минут
