### ISSUE TITLE
Реализовать отображение скачанных файлов(формат doc) на странице просмотра Источника

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#109]
**План решения:**
Поправить ссылки, добавить просмотр docx через iframe и google docs для админа и пользователя.
Добавить кнопку скачивания docx.
Добавить просмотр docx в источниках, которые не книги))

**Мотивация:**
Возникли проблемы с файлами doc, для нормальной работы надо их устранить

**Планируемое время:** 

2 часа

**Comment by AlexeyGoikolov** [comment]
Затрачено 2,5 часа. Были проблемы с настройкой Google и передачей правильной ссылки
