### ISSUE TITLE
Добавить функционал внесения категорий

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#11]
**Конечный результат:**

Реализовать пользователю с ролью "admin" возможность добавления категорий контента.

**План решения:**

В личном кабинете добавить кнопку "Добавить категорию".

Написать функционал создания администратором категорий контента и внесения в БД, для последующего применения при внесении Post. Привязать функционал к кнопке "Добавить категорию".

**Мотивация:**

По тех. заданию вносимый контент должен иметь категории

**Критерии приемки:**

У администратора в личном кабинете при нажатии на кнопку "Добавить категорию" должно открыться окно с формой для внесения категории и кнопка "Добавить". После добавления, категория должна быть записана в БД, для дальнейшего использования при внесении контента.

**Планируемое время работы:**
15 мин

**Comment by GalinaDugina** [comment]
не указано время
