### ISSUE TITLE
Добавить в таблицу в Библиотеке сортировку по БП

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#112]
**Мотивация:**
Заказчику необходимо фильтрация по БП

**План решения:**

На страницу со списком в Библиотеке добавить в таблицу колонку с БП
колонку тип файла убрать

**Критерии приемки:**
Отображается спиок  Библиотеки , есто колонка БП, можно осуществлять по ней сортировку

**Планируемое время:**

30 минут

**Comment by AlexeyGoikolov** [comment]
Затрачено 30 минут
