### ISSUE TITLE
Оставить сущность Книга, сущность Источник убрать

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#113]
**Мотивация:**
Сущности Book и Post пришли к состаянию идентичности, надо их объединить

**План решения:**
1. Изменить/удалить контроллеры на  админской и пользовательских частях
2. Просмотреть представления на добавление, редактирование, просмотр
3. Удалить сущность Post

**Критерии приемки:**
есть только сущность Post только при доабвлении книги открыты к заполнению одни поля, а при добавлении Источника другие

**Планируемое время:**

6 часов

**Comment by AlexeyGoikolov** [comment]
Затрачено 6, 5 часов. Возникли трудности с миграциями
