### ISSUE TITLE
Загрузка файлов в Книгу

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#114]
**Мотивация:**
При загрузке файла нужна подсказка: какие типы файлов можно загрузить и что делаь если у файла неподходящий тип

**План решения:**
1. Добавить рядом с кнопкой обзор письменное описание что разрешено
2. Использовать в теге input параметр accept

**Критерии приемки:**
на странице создания Книги возле поля по загрузке есть письменное описание что можно загрузить

**Планируемое время:**
40 минут

**Comment by AlexeyGoikolov** [comment]
Затрачено 40 минут
