### ISSUE TITLE
Подключить заполнение источника по ISBN через API 

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#116]
**Мотивация:**
В проекте необходимо реализовать работу API по добавлению данных о книге: это приятно заказчику и продемонстрирует навык работы с API

**План решения:**
[занятие по API](https://docs.google.com/document/d/1gaTAPADqYFpsIK3CUuQdKmEFaKln0I3SlYMKA0XXIIg/edit)
[примерный код на java](https://github.com/google/google-api-java-client-samples/blob/master/books-cmdline-sample/src/main/java/com/google/api/services/samples/books/cmdline/BooksSample.java)
[статические ссылки на книги](https://developers.google.com/books/docs/static-links)(можно использовать в коде)
[обсуждение как лучше](https://stackoverflow.com/questions/40410353/google-books-api-book-details-not-returned?rq=1) послать  запрос ISBN

1. Написать функцию : при вводе ISBN в окошко, расположить рядом кнопку "Заполнить по ISBN" по нажатию на которую отправляется Get запрос  на адрес https://www.googleapis.com/books/v1/volumes?q=
2. "Разложить" полученный Json по полям ввода данных о книге
примерный код 
 $("form").submit(
             function(e) {
               e.preventDefault();
               var isbn = $('#isbn').val();
               var isbn_without_hyphens = isbn.replace(/-/g, "");
               var googleAPI = "https://www.googleapis.com/books/v1/volumes?q=" + isbn_without_hyphens;
               $.getJSON(googleAPI, function(response) {
                 if (typeof response.items === "undefined") {
                   alert("Ничего не найдено по введеному ISBN")
                 } else {
                  $("#title").html(response.items[0].volumeInfo.title);
                  $("#name").val(response.items[0].volumeInfo.title);
                         $("#author").val(response.items[0].volumeInfo.authors[0]);
                         $("#publishedDate").html(response.items[0].volumeInfo.publishedDate);
                         $("#year").val(response.items[0].volumeInfo.publishedDate);
                 }
               });
             }
           )    
[ответ в виде Json ](https://www.googleapis.com/books/v1/volumes?q=isbn:9786010649316)- здесь можно посмотреть какие поля
3. Если ответ не пришел, вывести сообщение, о том что данных нет, надо заполнять вручную
4. Реализовать отправку данных в метод контроллера по созданию книги

**Критерии приемки:**
Когда я вношу информацию о книге
то в специальном поле ввожу код ISBN книги
тогда данные о названии книги , авторе и тд вносятся автоматически

**Планируемое время:**
3 часа

**Comment by GalinaDugina** [comment]
5 часов
