### ISSUE TITLE
Применить Data Seeding для заполнения БД

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#12]
**Конечный результат:**

Реализовать с помощью Data Seeding наполнение БД данными

**План решения:**

В проекте через модель GuideContext, либо с помощью пустой миграции описать наполнение сущностей БД данными

**Мотивация:**

Данный функционал необходим для работы над проектом и экономии во времени, так как не придется вручную добавлять данные во все сущности проекта.

**Критерии приемки:**

При запуске приложения, в БД автоматически запишутся данные, добавленные путем Data Seeding

**Планируемое время работы:**
15 мин

**Comment by GalinaDugina** [comment]
Добавить Категории, Типы, Должности (для регистрации сотрудника),

**Comment by GlebChuprin** [comment]
Планируемое время: 15 мин
Время по факту: 10 мин
