### ISSUE TITLE
Добавить возможность редактирования источника

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#121]
**Конечный результат:**

Реализованный функционал редактирования источника

**План решения:**

Добавить в контроллер SourceManage экшн Edit для редактирования источника. Добавить форму представления для внесения изменений по источнику.

**Мотивация:**

Источник должен иметь возможность редактироваться для внесения поправок и изменений

**Критерии приемки:**

При запуске проекта и переходе в источники, нажав на иконку "карандаш", открывается форма с заполненными данными по источнику. Данные должны иметь возможность корректироваться, после чего нажав на кнопку сохранить, данные перезаписываются в БД и у источника выходят обновленные данные.

**Планируемое время работы:**
4 часа

**Comment by GalinaDugina** [comment]
потратила 4 часа
