### ISSUE TITLE
Реализовать функционал загрузки файлов

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#13]
**Конечный результат:**

Реализовать возможность загрузки файлов в каталоги по типам и категориям контента при внесении сущности Post

**План решения:**

Добавить в проект возможность работы с подгрузкой файлов путем подключения FileUploadService в файле Startup.
Создать директории в каталоге wwwroot по типам контента

**Мотивация:**

По тех. заданию в проекте должна быть функция внесения и структурирования данных, для последующего поиска и работы с документами.

**Критерии приемки:**

Созданные в каталоге wwwroot подкаталоги по типам контента. Описанное подключение в файле Startup

**Планируемое время работы:**
1 час

**Comment by MuhtarLotov** [comment]
подключен  CKEditor для добавления видео через ссылку и для компонования текста
потрачено времени 20 м

**Comment by AlexeyGoikolov** [comment]
@MuhtarLotov  Необходимо сохранять книги в электронном варианте, а также аудио записи по каталогам при помощи FileUploadService. 
Нужно доработать

**Comment by GlebChuprin** [comment]
Планируемое время: 1 час
Время по факту: 1 час
