### ISSUE TITLE
Реализация функционала добавления данных сущности Post

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#14]
**Конечный результат:**

Добавить администратору возможность внесения данных в сущность Post

**План решения:**

Описать в контроллере метод по добавлению сущностей типа Post. Добавить форму представления для заполнения данных сущности.
Предусмотреть выпадающий список с возможностью выбора Типа и Категории контента.
Предусмотреть возможность подгрузки файла через форму.

**Мотивация:**

По ТЗ в базу данных должны будут вноситься текстовые данные, такие как книги, инструкции, правила.

**Критерии приемки:**

В личном кабинете администратора должна появиться кнопка добавления текстовых данных, на данном этапе кнопка "Добавить книгу". 
При нажатии на кнопку, должна открыться форма для заполнения данных. с выпадающим списком по категории и типу контента, а также возможностью подгрузки файла.
После заполнения данных и выбора электронного варианта книги либо инструкции, по нажатию на кнопку Добавить, данные должны быть внесены и сохранены в БД. Файл должен записаться в отдельную директорию по типу контента в каталоге wwwroot

**Планируемое время работы:**
4 часа

**Comment by GlebChuprin** [comment]
Планируемое время: 4-5 часа
Время по факту: 4 часа (проведенные за работой)
