### ISSUE TITLE
Реализация просмотра всех пользователей

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#15]
**Конечный результат:**

Добавить администратору возможность просмотра всех пользователей зарегистрированных в системе

**План решения:**

Реализовать представление по отображению всех пользователей. Добавить кнопку в личный кабинет администратора
Предусмотреть в отображении статус активности пользователя

**Мотивация:**

Администратор должен видеть всех пользователей, которые есть в системе, с их статусами активности.

**Критерии приемки:**

В личном кабинете администратора должна появиться кнопка "Все пользователи", при нажатии на которую, откроется таблица со списком всех пользователей.

**Планируемое время работы:**
      1 час

**Comment by MuhtarLotov** [comment]
Затраченная время на реализацию функционала : 1 час
