### ISSUE TITLE
Фильтр списка всех пользователей по статусу

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#16]
**Конечный результат:**

Добавить в представление отображения пользователей фильтрацию по статусу активности

**План решения:**

Описать в контроллере метод фильтрации пользователей по статусу активности, также добавить фильтр в представление со всеми пользователями

**Мотивация:**

У администратора должна быть возможность отфильтровать пользователей по их статусу в системе.

**Критерии приемки:**

При просмотре таблицы со всеми пользователями, сверху над таблицей, должна быть возможность выбора фильтра по статусу активности. Выбрав к примеру статус Активные, в списке должны остаться только активные пользователи.

**Планируемое время работы:**
1ч : 30м

**Comment by MuhtarLotov** [comment]
Затраченная время на реализацию функционала : 1ч : 30 м
