### ISSUE TITLE
Редактирование,отключение и подключение пользователя в списке всех пользователей

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#17]
**Конечный результат:**

Добавить в представление отображения пользователей дополнительное поле "Действие". В поле "Действие" добавить функционал отключения, подключения и редактирования данных пользователя.

**План решения:**

Добавить 2 кнопки: Подключить/Отключить и кнопку Редактировать в поле Действие в списке всех пользователей. На кнопку Подключить/Отключить повесить описанный функционал по удалению пользователя. 
Дополнить функционал метода по удалению, путем проверки статуса активности пользователя и в случае если активность false, менять на true.

На кнопку Редактировать, повесить функционал по изменению данных пользователя(Логин, Пароль)

Предусмотреть изменение названия кнопки в зависимости от статуса активности. Если пользователь имеет статус активен, то кнопка должна быть Отключить, если отключен, то кнопка должна быть Подключить

**Мотивация:**

У администратора должна быть возможность как удалить пользователя, так и вернуть его в активное состояние. Также должна быть возможность изменения данных пользователя, в случае неверно внесенных, или если забыт пароль.

**Критерии приемки:**

При просмотре таблицы со всеми пользователями, в поле действие должно быть 2 кнопки:
 Отключить/Подключить - кнопка отображает значение в зависимости от статуса и при нажатии изменяет статус пользователя в системе.
Кнопка Редактировать - при нажатии должно открываться поле для внесения изменений по пользователю, таких как логин и Пароль.

**Планируемое время работы:**
      1ч

**Comment by MuhtarLotov** [comment]
Затраченная время на реализацию функционала : 1ч : 30 м

**Comment by AlexeyGoikolov** [comment]
Не реализовано: Добавить 2 кнопки: Подключить/Отключить

Предусмотреть изменение названия кнопки в зависимости от статуса активности. Если пользователь имеет статус активен, то кнопка должна быть Отключить, если отключен, то кнопка должна быть Подключить  - **кнопка только удалить, после чего пользователь исчезает**

У администратора должна быть возможность как удалить пользователя, так и вернуть его в активное состояние - **после удаления, пользователь исчезает из списка**

Поправить верстку в виде таблицы
