### ISSUE TITLE
Дополнить модель User и миграцию БД

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#18]
**Конечный результат:**

Добавить модели User дополнительные поля и применить миграцию, для обновления сущности БД

**План решения:**

Описать свойства у модели User, добавить поля Имя, Фамилия, Должность.

Создать и применить миграцию БД.

**Мотивация:**

После встречи с заказчиком стало ясно, что ТЗ стало больше и необходимо увеличить данные о пользователях, путем добавления ФИО, Должности

**Критерии приемки:**

При открытии проекта и обновлении БД, в сущности User в БД должны появиться дополнительные поля Имя, Фамилия, Должность.

**Планируемое время работы:**
20 мин

**Comment by MuhtarLotov** [comment]
потраченное время 20м
