### ISSUE TITLE
Добавление полей при регистрации новых пользователей

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#19]
**Конечный результат:**

Добавить в форму регистрации новых пользователей поля Имя,Фамилия и Должность

**План решения:**

В форме регистрации добавить поля Имя, Фамилия и должность, обязательные для заполнения. После внесения данных в соответствующие поля, данные должны сохраняться в БД.

**Мотивация:**

Пользователи должны идентифицироваться по имени и фамилии, так как электронный адрес может не нести какой-либо информации о пользователе

**Критерии приемки:**

При открытии формы регистрации нового пользователя, должны появиться поля Имя, Фамилия и Должность. После создания нового пользователя, данная информация должна быть сохранена в БД.

**Планируемое время работы:**
1 ч 30 мин

**Comment by MuhtarLotov** [comment]
потраченное время 1ч 30м
