### ISSUE TITLE
Добавить отображение сущностей Post

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#20]
**Конечный результат:**

Добавить представление для сущности Post. Временно в шапке добавить кнопку на отображение списка Постов.
Отображать Посты списком, при выборе поста отображать данные поста подробно

**План решения:**

В каталоге представлений, добавить для сущности Post отображение в HTML. 

Предусмотреть внизу поста 2 кнопки: "Добавить комментарий" и "Задать вопрос".

Добавить в шапку кнопку "Посты"

**Мотивация:**

Для сущности типа Post по ТЗ должна быть возможность оставлять комментарии и задавать вопросы

**Критерии приемки:**

При переходе по кнопке "Посты" в шапке, должен открыться список всех постов. При выборе поста, он должен открыться подробно и внизу поста должны быть 2 кнопки  "Добавить комментарий" и "Задать вопрос"

**Планируемое время работы:**
1 час

**Comment by MuhtarLotov** [comment]
потраченное время 1ч
