### ISSUE TITLE
Реализовать функцию добавления комментария к посту

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#21]
**Конечный результат:**

Реализация функционала добавления комментария к сущности Post

**План решения:**

Описать в контроллере метод по добавлению комментариев к сущности Post. Добавить форму внесения комментария и подвязать к кнопке в отображении поста

**Мотивация:**

Для сущности типа Post по ТЗ должна быть возможность оставлять комментарии.

**Критерии приемки:**

При переходе к подробному отображению Поста и нажатии на кнопку "Добавить комментарий", должна открываться форма добавления комментария. После внесения комментария он должен быть внесен в БД и отобразиться внизу Поста в поле Комментарии

**Планируемое время работы:**
1час 20 мин

**Comment by MuhtarLotov** [comment]
потрачено времени 1ч 20м

**Comment by GalinaDugina** [comment]
коментарий добавляется только после обновления страницы
