### ISSUE TITLE
Реализация функционала Вопрос-Ответ(QuestionAnswer)

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#23]
**Конечный результат:**

Добавление администратором возможности заполнения сущности QuestionAnswer

**План решения:**

Описать в контроллере метод по добавлению данных в сущность QuestionAnswer. 
Добавить в сущность QuestionAnswer дату создания для последующей сортировки.

Добавить форму представления для заполнения данных.
Добавить представление на отображение данных Вопрос-Ответ из БД.

**Мотивация:**

По ТЗ в функционале проекта должен быть блок вопрос-ответ.

**Критерии приемки:**

При входе под администратором в шапке должен появиться пункт меню Вопрос-Ответ. При нажатии на данный пункт, должно открыться представление со всеми вопросами-ответами отсортированными по дате, от самых свежих до самых старых. и кнопкой добавить Вопрос-Ответ. При нажатии на добавить, открывается форма для заполнения данных. После внесения данных и нажатия кнопки "Добавить", заполненный Вопрос-Ответ должен отобразиться в общем блоке вопросов-ответов.

**Планируемое время работы:**
6 часов

**Comment by MuhtarLotov** [comment]
Затраченное время 6ч
пришлось поработать над сокращением кода из за дублирование кода
