### ISSUE TITLE
Реализовать внесение данных и отображение Глоссария

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#24]
**Конечный результат:**

Добавить в проект функционал добавления и отображения Глоссария

**План решения:**

Описать в контроллере функционал добавления Глоссария.
Добавить представления в каталоге Views на внесение и отображение сущности Glossary.

**Мотивация:**

По ТЗ в проекте должен присутствовать глоссарий с терминами и толкованиями терминов.

**Критерии приемки:**

После аутентификации в шапке сайта в меню, должна появиться кнопка Глоссарий, при нажатии на кнопку Глоссарий, должен открыться список всех внесенных терминов и пояснений отсортированный по алфавиту. Сверху над таблицей с терминами, должна быть кнопка "Добавить термин", при нажатии на которую, должна открыться форма по внесению термина и пояснения к нему. внизу должна быть кнопка "Добавить" при нажатии на которую, термин с пояснением должны записаться в БД и отобразиться в общем списке терминов.

**Планируемое время работы:**
4 часа

**Comment by MuhtarLotov** [comment]
затраченное время 4ч
