### ISSUE TITLE
Объединение функционала создания и просмотра пользователей

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#25]
**Конечный результат:**

Объединение функционала создания пользователя в пункте меню со списком сотрудников.

**План решения:**

Перенести пункт меню "Добавить пользователя" в виде кнопки в отображение всех пользователей в пункте меню  "Список сотрудников".
Переименовать пункт меню "Список сотрудников" в "Пользователи"

**Мотивация:**

Функционал по работе с пользователями необходимо сделать в одном месте, не разделяя на разные пункты меню.

**Критерии приемки:**

После аутентификации в шапке сайта в меню, должен появиться пункт "Пользователи" и исчезнуть пункт "Добавить пользователя". При переходе в пункт "Пользователи" должна появиться кнопка "Добавить пользователя" при нажатии на которую, откроется форма для создания нового пользователя.

**Планируемое время работы:**
5 мин

**Comment by MuhtarLotov** [comment]
затраченное время 5м
