### ISSUE TITLE
Создание сущности Книга и добавление представлений

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#26]
**Конечный результат:**

Добавить в проект сущность книга. Реализовать функционал добавления и отображения книг.

**План решения:**

Описать в каталоге Models сущность Book со следующими полями: Автор, Наименование, Год публикации, ISBN, Путь к сохраненному файлу, путь к сохраненной обложке, Физический путь(Местонахождение бумажной книги).

Создать и применить миграцию.

Описать в контроллере метод по добавлению книги в БД и сохранении подгружаемого файла в каталоге wwwroot/books
Добавить форму представления для внесения данных книги в проект, а также загрузки файла в каталог.
Добавить представление по отображению всех книг в виде списка, отсортированные по наименованию.

**Мотивация:**

По желанию заказчика, должна быть возможность сохранять книги в электронном формате, а также иметь представление о наличии бумажного варианта книги.

**Критерии приемки:**

В шапке проекта должен появиться пункт меню "Книги". При переходе в данный пункт, должны отобразиться списком все внесенные книги отсортированные по наименованию. Сверху добавить кнопку по "Добавить книгу" для внесения книги в БД. При нажатии на кнопку "Добавить книгу" должна открыться форма по внесению данных о книге.

**Планируемое время работы:**
3-4 часа

**Comment by GlebChuprin** [comment]
планируемое время: 3-4 часа
Время по факту: 4 часа 30 мин
