### ISSUE TITLE
Объединение функционала сущности Post и изменение формы добавления 

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#27]
**Конечный результат:**

Объединить добавление Постов и отображение всех Постов в одном блоке в меню и назвать "Материалы".
Изменить форму представления по внесению Поста на странице.

**План решения:**

Перенести пункт меню "Добавить Пост" в виде кнопки в пункт меню "Список Постов". 
Переименовать "Список Постов" в "Материалы".
Переименовать "Добавить Пост" в "Добавить материал".
Изменить в пункте меню "Материалы" заголовок "Список Постов" на "Список Материалов".
Кнопку "Добавить материал" разместить рядом с заголовком "Список Материалов"
В форме добавления поста переименовать поле "Название поста" в "Заголовок".
В форме добавления поста переименовать поле "Описание" в "Содержание".
Русифицировать заголовки таблицы.

Изменить форму добавления материала на таблицу с двумя колонками :

_Слева - Заголовок и Содержание_

_Справа - Автор, Категория, Файл,_ 

**Мотивация:**

Форма добавления материала должна быть понятна пользователю при прочтении. Функционал должен быть собран в одном месте, для удобства работы с материалами. Также форма добавления должна размещаться в пределах одного экрана без задействования скроллинга.

**Критерии приемки:**

При входе в проект в меню должен исчезнуть пункт "Добавить Пост" и вместо пункта "Список Постов" должен отображаться пункт "Материалы". При переходе в материалы, должен отобразиться список всех материалов, а также должна появиться кнопка "Добавить материал".  При нажатии на кнопку "Добавить материал", должна открыться форма для добавления материала в базу разбитая на 2 колонки и размещенная на одном экране без задействования скроллинга. 
Все пункты описанные в "Плане решения" по переименованиям, должны соответствовать названиям.

**Планируемое время работы:**
1 час 30 мин

**Comment by GlebChuprin** [comment]
Планируемое время: 1 час 30 мин
Время по факту: 1 час 15 мин
