### ISSUE TITLE
Доработать детальную страницу материала

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#28]
**Конечный результат:**

Аккуратная верстка, с правильно работающими комментариями

**План решения:**

1. Сверстать страницу Материала
2. Переделать функционал работы с комментариями:
    a. Создать PartialView CommentsPartial
    b. Добавить Ajax метод по подгрузке комментариев
    c. Добавить js код по работе с комментариями
    d. В форме комментария выводить автора комментария
    e. **Важно** передавать Id автора комментария из get запроса путем ViewBag либо созданием отдельной ViewModel
        Id нужно будет записать в отдельный Input с типом hidden и отправлять его значение в Ajax запросе 
    (Образец функционала находится в форме создания материала)
3. Реализовать кнопку "Задать вопрос" предусмотреть передачу Id материала
4. Переименовать страницу Preview в "Details"
5. Добавить Ajax удаление комментариев, админ в праве удалить любой комментарий, пользователь только свои (пример удаления путем Ajax реализовал по пути "Posts/Create, Posts/Create/CategoriesPartial")  

**Мотивация:**

Основной функционал должен быть готов для старта создания бизнес процесса, чем быстрее начнем, тем быстрее поймем какие трудности нас ждут

**Критерии приемки:**

При переходе на детальную страницу материала, должна отображаться аккуратная верстка с работающим функционалом отображения и добавления комментариев, комментарий будет содержать в себе дату, сообщение, и Имя автора

**Планируемое время работы:**
6 часов

**Comment by AlexeyGoikolov** [comment]
@GalinaDugina  при добавлении комментария, поле не очищается. Если после комментария нажать на "Просмотреть комментарии к этому материалу", то кнопка не работает. 
При удалении комментария, поле с комментариями закрывается и приходится нажимать опять на просмотр комментариев

**Comment by GalinaDugina** [comment]
Потрачено 6 часов, основное время ушло на поиск решения проблем с адаптацией к шаблону
