### ISSUE TITLE
Добавить Layout в проект 

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#29]
**Конечный результат:**

Шаблонная верстка без ненужных ссылок и правильно составленными правами доступа 

**План решения:**

1. Текущий Layout заменить Layout'ом из шаблона
2. В хедере разместить ссылки по разработанному функционалу
3. Ограничить доступ пользователя
4. Подобрать иконки для разделов
5. Убрать отображение Аватара из Layout

**Мотивация:**

Этот этап важен для вырисовывания общей картины о приложение, удобства перехода по полям.

**Критерии приемки:**

В Layout не должно быть ненужных полей, все скрипты подключения должны остаться неизменны

**Планируемое время работы:**
     3ч

**Comment by MuhtarLotov** [comment]
потраченное время 4ч 
возникло конфликты с подтянутыми скриптами
