### ISSUE TITLE
Скоректировать работу с CKEditor

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#30]
**Конечный результат:**

При детальном просмотре материала поле с содержанием отображается через CKEditor (без Toolbar)
При создание материала поле "Содержание" создается в форме CKEfitor

**План решения:**

1. Подключить скрипты CKEditor в Layout 
2. Подключить CKEditor в форме создания материала для поля "Содержание"
3. Подключить CKEdtior при отображение детальной страницы материала 
4. Отключить Toolbar на детальной страницы материала

**Мотивация:**

Многий функционал описанный заказчиком легко реализуется путем внедрения сторонних программ в приложение, но для того чтобы этот функционал был реализован его нужно правильно настроить

**Критерии приемки:**

При переходе на детальную страницу материала поле "Содержание" выводится без скриптов и Toolbar, при создание материала поле "Содержание" заполняется в форме CKEditor

**Планируемое время работы:**
40 минут

**Comment by GalinaDugina** [comment]
затраченное время 40 минут. Основное время ушло на изучение информации
