### ISSUE TITLE
Валидация создания материала

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#31]
**Конечный результат:**

Материал при создании должен проходить проверку на валидность 

**План решения:**

1. в модели PostCreateViewModel добавить поля валидации
    a. Поле Title обязательно
    b. Поле Author обязательно
    c. Поле CategoryId обязательно
    d. Поле TypeId обязательно
2. Добавить Span с выводом ошибки под каждой поле проходящее валидацию
3. Добавить скрипт на постоянную проверку на валидность (Проверка должна происходить до момента отправки формы)
4. Добавить проверку на валидность в Action Create [POST] Controller Post 

**Мотивация:**

Важно доработать мелкие аспекты скелета приложение такие как валидность для перехода к следующим этап

**Критерии приемки:**

Материал не создается если он невалиден,
Проверка проходит в соответствии с указаниями
Проверка должна происходить до момента отправки формы

**Планируемое время работы:**
1 час

**Comment by GalinaDugina** [comment]
потрачено 15 минут
