### ISSUE TITLE
Валидация создания книги

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#32]
**Конечный результат:**

Материал при создании должен проходить проверку на валидность 

**План решения:**

1. В модели BookCreateViewModel добавить поля валидации
    a. Поле Name обязательно
    b. Поле Author обязательно
    c. Поле VirtualPath обязательно
    d. Поле YearOfWriting обязательно, не больше и не меньше 4 символом
2. Добавить Span с выводом ошибки под каждой поле проходящее валидацию
3. Добавить скрипт на постоянную проверку на валидность (Проверка должна происходить до момента отправки формы)
4. Добавить проверку на валидность в Action Create [POST] Controller Book

**Мотивация:**

Важно доработать мелкие аспекты скелета приложение такие как валидность для перехода к следующим этап

**Критерии приемки:**

Материал не создается если он невалиден,
Проверка проходит в соответствии с указаниями
Проверка должна происходить до момента отправки формы

**Планируемое время работы:**
  1ч

**Comment by MuhtarLotov** [comment]
затраченное время 1ч
