### ISSUE TITLE
Добавить сущность Шаблон, подгружать ее в CKEditor

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#33]
**Конечный результат:**

при создании материала должно быть возможно выбрать из выпадающего списка шаблон и подгрузить его в поле CKEditor, создать шаблон, редактировать шаблон, удалить шаблон 

**План решения:**
1. Добавить сущность "Template"
  с полями : Id, Name, Text
2. Реализовать добавление шаблона, желательно из формы материала :
   a. Разместить кнопку "Создать шаблон" рядом с полем CKEditor
   b. По нажатию на нее будет выпадать модальное окно
   c. В модальном окне расположить CKEditor и Input
   d. Записать в поле CKEditor текст находящийся в поле "Содержание" в форме материала
   e. Предложить назвать шаблон и сохранить его.
3. Реализовать Ajax подгрузку шаблонов в поле CKEditor по выбору

**Мотивация:**

Важный шаг перед началом реализации бизнес процессов

**Критерии приемки:**

Шаблон нельзя создать с пустым именем или содержанием
Шаблон сохраняет всю работу над текстом
Шаблон создается из формы создания материала
Шаблон создается без перезагрузки страницы

**Планируемое время работы:**
4ч

**Comment by MuhtarLotov** [comment]
потраченное время 5ч
были затруднения с погрузкой шаблона в CKEditor
