### ISSUE TITLE
В Материалах подправить верстку

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#34]
**Конечный результат:**

Автор и кнопка добавления перенесены в право

**План решения:**

1. Перенести поле "Автор" в право
2. Перенести кнопку добавления в право

**Мотивация:**

Добавилось поле шаблон, нужна переверстка страницы

**Критерии приемки:**

Поле Автор находится справа
Кнопка добавления находится справа

**Планируемое время работы:**
            15м

**Comment by MuhtarLotov** [comment]
затраченное время 15м
