### ISSUE TITLE
Для админа добавить отображение таблиц из шаблона Minovate 

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#35]
**Конечный результат:**

Добавить шаблон таблицы по примеру Minovate (пример: Tables->DataTables->вторая таблица сверху)

**План решения:**

Изменить в представлениях, где использованы таблицы верстку по шаблону с возможностью поиска. За основу взять таблицу из DataTables Minovate

**Мотивация:**

У администратора должен быть удобный функционал просмотра всей внесенной информации и действий над ними

**Критерии приемки:**

При входе под администратором в просмотр внесенных данных, таких как материалы, книги, глоссарий, пользователи, отображение должно быть по шаблону Minovate

**Планируемое время работы:**
4,5 часа

**Comment by GalinaDugina** [comment]
потрачено времени 5 часов, из за проблем адаптации с шаблона
