### ISSUE TITLE
Сверстать отображение книг для админа списком 

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#36]
**Конечный результат:**

Для администратора сверстать отображение книг списком

**План решения:**

Создать отдельное представление для отображения всех книг списком в виде таблицы без миниатюр.

Представление с миниатюрами оставить для публичной части.

**Мотивация:**

Реализовать для администратора удобный функциональный интерфейс для работы с книгами

**Критерии приемки:**

При входе под администратором в списке книг не должны отображаться миниатюры книг и верстка должна быть в виде таблицы по примеру DataTables Minovate

**Планируемое время работы:**
20  минут

**Comment by GalinaDugina** [comment]
потраченное время 20 минут,
