### ISSUE TITLE
Дополнение сущности Глоссарий и изменение отображений

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#37]
**Конечный результат:**

Добавить поля в сущность Глоссарий. Изменить представления по внесению и отображению сущности

**План решения:**

Добавить в сущность Глоссарий следующие поля: Аббревиатура и Источник.
Добавить в форму добавления данных в Глоссарий новые поля для заполнения.
В списке всех терминов и при детальном просмотре добавить новые поля для отображения.
Изменить экшены в контроллере для обработки внесения новых полей.

**Мотивация:**

По видению заказчика в Глоссарий необходимо добавить "Аббревиатуру" и "Источник".

**Критерии приемки:**

При добавлении нового термина в глоссарий, в форме внесения данных должны отобразиться новые поля "Аббревиатура" и "Источник". После внесения данных, при переходе на список терминов, в таблице должны быть отображены данные поля. Также при детальном просмотре, новые поля должны быть добавлены.

**Планируемое время работы:**
1ч

**Comment by MuhtarLotov** [comment]
потраченное время 1ч 30м было добавлено ckeditor в описание и изменен стилизация  добавления глосоря
