### ISSUE TITLE
Добавить возможность редактирования для всех сущностей

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#38]
**Конечный результат:**

Добавление форм редактирования информации по всем сущностям.

**План решения:**

Для каждой сущности в проекте, необходимо описать в контроллере методы по редактированию информации. Редактирование должно быть задействовано с помощью форм внесения

**Мотивация:**

Необходимо иметь возможность редактирования внесенной в БД информации для исправления ошибок и актуализации информации.

**Критерии приемки:**

При просмотре сущностей Материалы, Книги, Глоссарий, Пользователи, Вопрос-Ответ должна появиться кнопка "Редактировать" при нажатии на которую откроется форма с заполненными полями из БД и возможностью внесения корректировок и сохранения в БД.

**Планируемое время работы:**
2ч

**Comment by MuhtarLotov** [comment]
потраченное время 1ч 30м
