### ISSUE TITLE
Изменить Title

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#39]
**Конечный результат:**

Title каждой страницы отображается в едином стиле шаблона Minovate

**План решения:**

1. Просмотреть код страницы шаблона с примером Title
2. Заменить существующие стили на стили шаблона

**Мотивация:**

Верстка должна отображаться в едином стиле

**Критерии приемки:**

Все поля Tilte на сайте отображаются в стиле шаблона Minovate

**Планируемое время работы:**
2 часа

**Comment by AlexeyGoikolov** [comment]
Затраченное время - 3 часа.
Пришлось также корректировать верстку для более аккуратного представления.
