### ISSUE TITLE
Детальная страница книги

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#40]
**Конечный результат:**

Детальная страница книги аккуратно сверстана и адаптирована к Шаблону Minovate
**План решения:**

1. Добавить верстку страницы Details
2. Скорректировать надпись "Код книги" добавив в скобках "(ISBN)"
3. Должна быть возможность просмотреть скачанную книгу

**Мотивация:**

Все этапы отображения должны быть сделаны для без проблемной работы с сущностями

**Критерии приемки:**

Детальная страница сверстана и на ней отображается вся информация о книге

**Планируемое время работы:**
3 часа

**Comment by GalinaDugina** [comment]
потрачено 3 часа, много времени ушло на поиск решения по просмотру книги
