### ISSUE TITLE
Удаление книг

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#41]
**Конечный результат:**

удаление книг происходит по типу Active (false/true)
удаленные книги можно просмотреть админу

**План решения:**

1. Добавить книге поле (bool) Active
2. Добавить метод удаления книги Active = false
3. Добавить фильтрацию книг ( выгружать только не удаленные )
4. Добавить отображение удаленных книг для админа ( не в общем списке )

**Мотивация:**

Мы должны иметь возможность снести ненужную книги, при этом не запутать данные ссылающиеся на эту книгу

**Критерии приемки:**

Книгу можно удалить
Книга не удаляется из базы данных
Админ может просматривать удаленные книги

**Планируемое время работы:**
1ч

**Comment by MuhtarLotov** [comment]
затраченное время 1ч
