### ISSUE TITLE
Адаптировать форму регистрации сотрудников под Шаблон

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#42]
**Конечный результат:**

Форма регистрации нового сотрудника  должна быть взята из шаблона Minovate

**План решения:**

1. Достать код верстки из шаблона
2. Инициализировать его в приложение

**Мотивация:**

Все части приложения должны быть в едином дизайне

**Критерии приемки:**

Страница регистрации в приложение и в шаблоне должны совпадать
Весь функционал должен так же безошибочно работать

**Планируемое время работы:**
1 час

**Comment by AlexeyGoikolov** [comment]
Затраченное время - 1 час

**Comment by AlexeyGoikolov** [comment]
Добавил корректировки. Затраченное время 15 минут
