### ISSUE TITLE
Русифицировать элементы Шаблона

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#43]
**Конечный результат:**

В Таблицах, задействованных в проекте -  поля: пагинация, поиск и информационные сообщения должны выводиться на русском языке .

**План решения:**

Изучить файлы Js, содержащиеся в шаблоне Minovate и внести необходимые изменения.

**Мотивация:**
Проект должен быть написан на одном языке .

**Критерии приемки:**

При просмотре  Таблиц в проекте вся служебная информация отображается на русском языке.

**Планируемое время работы:**
1 час

**Comment by AlexeyGoikolov** [comment]
Затраченное время 45 минут
