### ISSUE TITLE
Переверстать в соответствии с Шаблоном Форму входа в приложение

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#44]
**Конечный результат:**

Форма входа в систему должна быть взята из шаблона Minovate

**План решения:**

Достать код верстки из шаблона
Инициализировать его в приложение
**Мотивация:**

Все части приложения должны быть в едином дизайне

**Критерии приемки:**

Страница входа в приложение и в шаблоне должны совпадать
Весь функционал должен так же безошибочно работать

Планируемое время работы:
1ч

**Comment by MuhtarLotov** [comment]
потраченное время 1ч 10м
