### ISSUE TITLE
Переверстать в соответствии с Шаблоном форму просмотра Материала

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#45]
**Конечный результат:**
Аккуратная верстка страницы просмотра Материала

**План решения:**

Достать код верстки из шаблона
Инициализировать его в приложение
По верстке ориентироваться на страницу Создания материала
Для админа просмотр материала аналогичен его редактированию , то есть и есть редактирование
Для пользователя просто просмотр

**Мотивация:**

Все части приложения должны быть в едином дизайне

**Критерии приемки:**

При переходе на вкладку просмотра Материала верстка должна быть аккуратной по аналогии с версткой по созданию Материала

**Планируемое время работы:**
1ч

**Comment by MuhtarLotov** [comment]
затраченное время 1ч
