### ISSUE TITLE
Устранить неисправность на странице просмотра пользователей

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#46]
**Конечный результат:**

При просмотре страницы со списком пользователей работает весь функционал

**План решения:**

1. При адаптации с Шаблоном возникла проблема: на корректно работает функционал по фильтрации пользователей.
Надо поэтапно проверить работу программы и найти причину.
2. При нажатии кнопки : "Добавить в бизнес процесс"  надо получить возможность поменять должность ( Position ) для пользователя, то есть должность у нас = задача на которую принят сотрудник

**Мотивация:**

Реализовать Шаг1 из Карты шагов, от заказчика

**Критерии приемки:**

Админ открывает страницу просмотра сотрудников может выбрать для просмотра активных/не активных/всех  используя фильтрацию.
Админ может поменять  сотруднику со статусом активен  значение поля: должность ( Position ) 

**Планируемое время работы:**
4,5 часа

**Comment by AlexeyGoikolov** [comment]
Затраченное время 4 часа 50 минут.  Возникли проблемы с модальным окном и скриптом JS
