### ISSUE TITLE
Разделить проект на две части : клиентскую и для админа

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#47]
**Конечный результат:**
При входе в приложение под паролем User происходит переход на страницу, на которой в меню доступен только просмотр.

**План решения:**
информация:
[мастер-страница](https://metanit.com/sharp/mvc5/4.3.php)
[области](https://docs.microsoft.com/ru-ru/aspnet/core/mvc/controllers/areas?view=aspnetcore-3.1)
[маршрутизация](https://professorweb.ru/my/ASP_NET/mvc/level3/3_4.php)

1. Разделить проект на области Employee, Admin (если сочтете нужным можно на области не делить: обойтись просто контроллером)(и тут еще сложность: в Raider такую возможность не понятно как найти)
2. Создать  второй файл _LayoutEmployee, на основе уже имеющегося по шаблону другого цвета, но в Меню  убрать те пункты в которых происходит переход на  добавление : Материала, Книги,Вопроса, Термина.
 Пункт меню по работе с пользователями убрать.
 _Идея в том , что доступен только просмотр._
3. Добавить в проект EmployeesController инициализировать его через  базу данных и UserManager в конструкторе и добавить необходимые представления
4. Добавить Employees  представления для просмотра списка и детально : книг,материалов, терминов, вопросов на подложке _LayoutEmployee
@{
       Layout = "_LayoutEmployee "
}
5. В      AccountController  необходимо внести корректировки, чтобы при входе в приложение User происходил преход на Details то есть в личный кабинет сотрудника на _LayoutEmployee 
6. возможно в процессе работы будут добавлены новые пункты, так как реализация происходит впервые 

**Мотивация:**
Чтобы создать возможность ссылаться на объекты, хранящиеся в БД необходимо создать в проекте структуру разделения на отдельные функциональные части: для сотрудника, который изучает информацию и для администратора, который создает и управляет информацией.

**Критерии приемки:**
При входе в приложение под паролем User происходит переход на страницу, на которой в меню доступен только просмотр.

**Планируемое время работы:**
18 часов

**Comment by AlexeyGoikolov** [comment]
Затраченное время 16 часов 30 минут.
