### ISSUE TITLE
Поменять Id  с формата string  на int

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#49]
**Конечный результат:**

Во всех моделях, кроме user,  Id должно быть integer 

**План решения:**
Поменять во всех моделях ID  с srting  на int
Сделать миграции

**Мотивация:**

При создании линка на модель : ID  в виде строки очень длинный и сбивает с толку, рациональнее использовать ID  в виде числа

**Критерии приемки:**
При просмотре Материала или Книги : URL красивый и лаконичный

**Планируемое время работы:**
1,5 часа

**Comment by AlexeyGoikolov** [comment]
Затраченное время 1,5 часа
