### ISSUE TITLE
Добавить аутентификацию

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#5]
**Конечный результат:**

Добавить аутентификацию в проект для проверки подлинности данных, предоставленных пользователем для доступа к запрашиваемым им ресурсам

**План решения:**

При помощи Identity описать контроллер Account с функционалом регистрации и входом пользователя

**Мотивация:**

Заказчику необходимо, чтобы доступ предоставлялся по логину и паролю.

**Критерии приемки:**

Описанный контроллер с функционалом регистрации и входа пользователя.
При запуске проекта, открывается страница с формой ввода логина и пароля. При правильном вводе, после нажатия кнопки "Войти", пользователь проходит аутентификацию и заходит в систему.

**Планируемое время работы:**
4-5 часа

**Comment by GlebChuprin** [comment]
Предполагаемое время: 4-5 часа
Время по факту: 4 часа 30 мин

**Comment by AlexeyGoikolov** [comment]
Выполнено
