### ISSUE TITLE
Личный кабинет сотрудника

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#50]
**Конечный результат:**

Сотрудник входит по паролю в приложение и попадает в личный кабинет

**План решения:**
1. Найти красивое фото в интеренете на тему : "Дружная команда" сохранить его в root проекта
2. Сверстать красивое приветствие: "Добро пожаловать _Name + SurName_ . Ваша задача  : _Position_"
3. Внизу от приветствия разместить заготовленное фото во весь экран

**Мотивация:**
Создать приветствие сотруднику при входе в приложение

**Критерии приемки:**

>Если я при входе в приложение  ввожу логин  User 
> То я  перехожу на личную страницу и вижу приветствие с обращением ко мне по имени

**Планируемое время работы:**
2 часа

**Comment by AlexeyGoikolov** [comment]
Затраченное время 2 часа
