### ISSUE TITLE
Переверстать добавления книги

### ISSUE THREAD

**Issue by MuhtarLotov** [CSharp2-3Command2/Guide#51]
**Конечный результат:**
Аккуратная верстка страницы добавления книг
Все поля должны быть в белом фоне
Добавлена поля категория с возможностью создавать новый категории 

**План решения:**
Вставить белый фон за полями 
Добавить поля категория с возможностью создавать новый категории для админа

**Мотивация:**

Аккуратная верстка страницы
Разделения книг по категориям в том же числе и рецепт по желанию клиента

**Критерии приемки:**

При переходе на вкладку добавить книгу верстка должна быть аккуратной по аналогии с версткой по созданию Материала

Планируемое время работы:
2 часа

**Comment by GalinaDugina** [comment]
потрачено 2 часа
