### ISSUE TITLE
Доработать вопрос ответ 

### ISSUE THREAD

**Issue by MuhtarLotov** [CSharp2-3Command2/Guide#52]
Конечный результат:
при отправке вопроса должно сохраниться данные о пользователе и создаться статус новый 
при ответе должно сохраниться данные сотрудника ответившего на вопрос и поменяться статус на ответили 
при открытие ответа на вопрос пользователем статус поменяться на прочитан

План решения:

добавить к модели QuestionAnswer
id пользователя задавший вопрос
id пользователя ответившего на вопрос
добавить статус -новый
                            - ответили 
                            - прочитан

Мотивация:
нужно хранить информацию о пользователе задавшего вопрос и пользователе ответившего на вопрос для просмотра и донесения информацию к пользователю задавшего вопрос 
статус для уведомления пользователя об новом ответе на вопросе

Критерии приемки:

при отправке вопроса должно сохраниться данные о пользователе и создаться статус новый 
при ответе должно сохраниться данные сотрудника ответившего на вопрос и поменяться статус на ответили 
при открытие ответа на вопрос пользователем задавший вопрос статус поменяться на прочитан

Планируемое время работы:
2 часа

**Comment by GalinaDugina** [comment]
потрачено 2 часа
