### ISSUE TITLE
Разгрузка вопросов

### ISSUE THREAD

**Issue by MuhtarLotov** [CSharp2-3Command2/Guide#53]
**Конечный результат:**

Возможность задать вопрос  должен быть в конце списка и выходить при отсутствие совпадении в поиске 

**План решения:**

убрать возможность задать вопрос из  меню
добавить возможность задать вопрос в конец списка 

**Мотивация:**

у пользователя не должно быть возможность сразу задать вопрос без поиска чтобы уменьшить одинаковых задаваемых вопросов 

**Критерии приемки:**

 Возможность задать вопрос должно выходить последним в списке или после поиска при отсутствии совпадавшего вопроса

**Планируемое время работы:**
3 часа

**Comment by AlexeyGoikolov** [comment]
Затраченное время  3 часа. Реализовывал через JS
