### ISSUE TITLE
Добавить переход в публичную часть

### ISSUE THREAD

**Issue by MuhtarLotov** [CSharp2-3Command2/Guide#54]
Конечный результат:

Из списка материалов можно открыть публичный часть материала  и все действия в виде иконок

План решения:

Добавить в списке материалов к действиям вид пользователя который будет открывать публичную часть материла
Все действия сделать в виде иконок   

Мотивация:

добавить в списке материалов к действиям вид пользователя который будет открывать публичную часть материла чтобы иметь ссылки на добавление
Все действия сделать в виде иконок  для визуальной красоты и компоновки

Критерии приемки:

Из списка материалов можно открыть публичный часть материала  и все действия в виде иконок

Планируемое время работы:
30 минут

**Comment by AlexeyGoikolov** [comment]
Затраченное время 30 минут
