### ISSUE TITLE
Отображения материалов  для пользователя 

### ISSUE THREAD

**Issue by MuhtarLotov** [CSharp2-3Command2/Guide#55]
**Конечный результат:**

 по ссылке открывается вид на материла без возможности редактирования 

**План решения:**

Сверстать отображения материалов для пользователя без возможности редактирования 
добавить возможность комментировать

**Мотивация:**

у пользователя должна была возможность открывать и ознакомиться материалом 

**Планируемое время работы:**
2 часа

**Comment by GalinaDugina** [comment]
потрачено 2 часа
