### ISSUE TITLE
Добавить фильтр к списку материалов

### ISSUE THREAD

**Issue by MuhtarLotov** [CSharp2-3Command2/Guide#59]
**Конечный результат:**

в списке материалов должна быть функция фильтрации по Тип Контента, Категория, Тип Файла, Состояние

**План решения:**

добавить функционал фильтрации по Тип Контента, Категория, Тип Файла, Состояние

**Мотивация:**

Фильтрация нужна чтобы отсортировать список по интересующему Типу или Категория информации

**Планируемое время работы:**

**Comment by GalinaDugina** [comment]
после встречи с заказчиком, потеряла свою актуальность
