### ISSUE TITLE
Добавить роли для пользователей

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#6]
**Конечный результат:**

Добавить в проект на данном этапе 2 роли "admin" и "user"

**План решения:**

Используя функционал Identity, описать логику присвоения ролей пользователям. Предусмотреть создание пользователя
с ролью "admin" при старте проекта

**Мотивация:**

По тех. заданию необходимо предоставление доступов с разными уровнями доступа

**Критерии приемки:**

Реализованный функционал добавления ролей "admin" и "user" в проекте. 
При первом запуске проекта, в БД должен появиться пользователь с правами доступа "admin"

**Планируемое время работы:**
1-2 часа

**Comment by GlebChuprin** [comment]
Предполагаемое время: 1-2 часа
Время по факту: 1 час
