### ISSUE TITLE
Шаблоны для БП

### ISSUE THREAD

**Issue by MuhtarLotov** [CSharp2-3Command2/Guide#60]
**Конечный результат:**

Будет список шаблонов в котором будет возможность скачать шаблон

**План решения:**

сверстать список шаблонов в нем добавить функционал загрузки шаблона 
и чтобы и можно было скачать по ссылке

**Мотивация:**

Шаблоны нужны чтобы прекратить их к задачам для скачивания 

**Планируемое время работы:**

**Comment by GalinaDugina** [comment]
сейчас  не актуальна

**Comment by GalinaDugina** [comment]
вообще не актуально
