### ISSUE TITLE
Устранить проблему при регистрации User

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#61]
**Конечный результат:**

После регистрации пользователя ему добавляется роль  : User. При редактировании данных пользователя можно поменять ему роль на  Admin ( в этом так же задел на будущее, если будут еще роли)
**План решения:**
1. В контроллере Account в метод Register внести изменения:
                    IdentityRole role = await _roleManager.FindByNameAsync("admin") ;
                    await _userManager.AddToRoleAsync(user, role.Name);                   
                    await _signInManager.SignInAsync(user, false);
                   
2. В редактированиe данныx о User сделать возможным  присвоить роль Admin, роль user присваивается всем по умолчанию при регистрации.
3. Провести пробную регистрацию

4.Проверить в БД создание ролей : в таблице Роли и у User

**Мотивация:**

В настоящий момент программа работает с ошибкой, при регистрации пользователя не добавляется никакой роли, нам надо добавлять пользователю роль User и так же иметь возможность давать права админа 

**Критерии приемки:**

Если я захожу в программу под паролем для Admin
То могу регистрировать пользователя, он получает роль User
Если я редактирую данные пользователя то могу изменить его роль на Admin

**Планируемое время работы:**
30м

**Comment by MuhtarLotov** [comment]
потрачено 30м
