### ISSUE TITLE
Изменить сущность термин

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#62]
**Конечный результат:**

В Глоссарии - Термины - имеют несколько  Толкований+Аббревиатура
**План решения:**
1. Внести изменения в сущность Термин: он будет содержать только название
2. Создать сущность Толкование : содержит три текстовых поля: описание и аббревиатура, источник, и ID термина
3. На странице ввода термина организовать возможность ввести несколько толкований (см.создание комментариев)
4. Для ввода использовать ckeditor (чтобы была возможность форматирования текста и добавления ссылок)
5. У админа: возможность создавать и редактировать Термины, просматривать Термины на странице пользователя
6. У пользователя только промотр списка терминов и при клике подробный просмотр со всеми описаниями.

**Мотивация:**

Заказчик сообщила, что у термина может быть не одно,  а несколько толкований, аббревиатур с сылкой на источник. Надо это реализовать

**Критерии приемки:**

Если я захожу в программу под паролем для Admin
То могу создать Термин
И добавить к нему любое количество Толкований

Если я захожу в программу как пользователь
То могу просмотреть в Глоссарии спиок терминов
И нажав на название термина, просмотреть все толкования

**Планируемое время работы:**
5 часов

**Comment by GlebChuprin** [comment]
7 часов 50 мин
