### ISSUE TITLE
Изменение в меню "Материалы" на "Библиотека", перенесение "Книги" в "Библиотеку"

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#63]
**Конечный результат:**

В меню добавить пункт Библиотека и перенести книги.

**План решения:**

Изменить пункт меню "Материалы" на "Библиотека".  Пункт меню "Книги" перенести в "Библиотека". У книг убрать поля "Список" и "Добавить". Сделать ссылку на список книг по нажатию на "Книги".  Также добавить пункт в библиотеку Источники.

**Мотивация:**

По согласованию с заказчиком, определили, что все источники будут в меню Библиотека. Термин "Материалы" принято исключить из проекта. 

**Критерии приемки:**

При входе в проект под администратором, в левом меню отображается пункт "Библиотека" и отсутствуют пункты "Материалы" и "Книги". При нажатии на библиотеку, раскрывается список Источники и Книги. При нажатии на Источники, открывается список источников в таблице. При нажатии на Книги, открывается список с книгами. 

**Планируемое время работы:**
30 мин

**Comment by GlebChuprin** [comment]
Планируемое время: 30 мин
затраченное время: 1 час
Большая часть время ушла, на понимание ЖР тикета
