### ISSUE TITLE
Изменить форму редактирования пользователя

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#64]
**Конечный результат:**

В форме редактирования пользователя, должны быть доступны все поля для редактирования. В личном кабинете пользователя должна быть кнопка для администратора - "Редактировать профиль".

**План решения:**

Изменить форму представления редактирования пользователя, путем добавления отсутствующих полей для возможности внесения корректировок.

Добавить в личном кабинете пользователя кнопку "Редактировать профиль", доступную только для администратора.

Переверстать форму редактирования по шаблону Minovate, одинаковую с формой регистрации пользователя.

**Мотивация:**

В проекте необходима возможность корректировки всех полей пользователя.

**Критерии приемки:**

При входе в проект под администратором,  выбрав у пользователя пункт редактировать, должна открыться форма корректировки данных о пользователе со всеми возможными полями пользователя.

**Планируемое время работы:**
1ч

**Comment by MuhtarLotov** [comment]
потраченное время 2ч были не непредвиденные сложности
