### ISSUE TITLE
Отображение файла при загрузке источника(Материала)

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#65]
**Конечный результат:**

Отображение файла в материале в случае, если файл был добавлен

**План решения:**

Добавить отображение файла(картинки), который возможно подгрузить в материалах, сразу после содержания

**Мотивация:**

В материалах(Источниках) есть возможность подгрузить файл, но данный файл нигде не отображается. Должна быть возможность просмотреть файл

**Критерии приемки:**

При загрузке Материала(Источника), выбрав файл и сохранив материал(источник), после его открытия, файл должен отображаться ниже содержания.

**Планируемое время работы:**
1 час

**Comment by GalinaDugina** [comment]
потрачено 1 час
