### ISSUE TITLE
Изменить FAQ(Вопрос-ответ) на Ситуационную базу

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#66]
**Конечный результат:**

В меню у администратора и пользователя вместо пунктов меню Вопрос-ответ и FAQ  присутствует пункт "Ситуационная база".

**План решения:**

Изменить пункт меню FAQ(Вопрос-ответ) на "Ситуационная база".
Изменить названия в полях ввода информации с Вопрос на Ситуация.
Изменить названия в полях ввода информации с Ответ на Решение ситуации.
Добавить CKEditor для внесения решения ситуации.

**Мотивация:**

Заказчик видит базу вопрос-ответ, как Ситуационная база. Также для добавления ссылок, необходим текстовый редактор CKEditor, вместо textarea

**Критерии приемки:**

При входе в проект под администратором, в меню слева присутствует пункт "Ситуационная база". При нажатии открывается список: "Ситуации с решениями" , "Ситуации без решений" и Добавить ситуацию". При нажатии на "Добавить ситуацию" открывается страница с полями ввода "Ситуация" и "Решение ситуации". "Решение ситуации" реализовано при помощи CKEditor.
При входе под пользователем, в меню слева есть пункт "Ситуационная база". При нажатии на пункт меню, открывается страница со списком всех ситуаций. 

**Планируемое время работы:**
2 часа

**Comment by GalinaDugina** [comment]
потрачено 2 часа, дополнительно поменяла верстку
