### ISSUE TITLE
Реализовать личный кабинет администратора

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#7]
**Конечный результат:**

Реализовать личный кабинет для администратора для дальнейшего наполнения функционалом

**План решения:**

Добавить представление(верстку) личного кабинета для пользователя с правами "admin"

**Мотивация:**

У администратора будет определенный функционал( добавление пользователей, наполнение информацией и т.д.), который необходимо отобразить для выбора. По ходу развития проекта функционал будет пополняться.

**Критерии приемки:**

После ввода логина и пароля администратора, откроется личный кабинет, в котором будут отрисованы кнопки добавления и удаления пользователей, и добавления информации на данном этапе. 

**Планируемое время работы:**
1 час

**Comment by GalinaDugina** [comment]
не указано планируемое и затраченное время
