### ISSUE TITLE
Реализация обработки публичной части отображения задач и шагов в контроллере

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#70]
**Конечный результат:**

Реализованный функционал отображения задач и шагов в иерархическом порядке в контроллере _при просмотре страницы Details сотрудника_

**План решения:**

Реализовать контроллер в публичной части и описать логику взаимодействия пользователя с задачами и шагами, путем вывода связей из промежуточной таблицы IssueStep.
Предусмотреть отображение шагов в том порядке, в котором они были выстроены при добавлении в задачу.

**Мотивация:**

Программа по обучению пользователей, должна быть организована в иерархическом порядке по шагам и задачам внутри. Пользователь должен видеть задачу, а зайдя в нее, видеть описание и шаги для прохождения шагов.

**Критерии приемки:**

Зайдя под пользователем в систему, пользователь видит назначенные ему задачи, либо шаги. Перейдя в задачу, пользователь видит название задачи, ее описание и ниже шаги, которые ему необходимо пройти. Нажав на шаг, пользователь переходит непосредственно к шагу, который ему необходимо изучить.

**Планируемое время работы:**
4 часа

**Comment by GalinaDugina** [comment]
потрачено 5 часов
