### ISSUE TITLE
Реализовать сущность "Желаемый результат" и добавление к шагам и задачам

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#71]
**Конечный результат:**

Сущность в БД, в которую будут добавляться Желаемые результаты и присваиваться шагам и задачам

**План решения:**

Описать модель Желаемый результат(далее ЖР), состоящей из Id и названия. Добавить модель в таблицы БД. Реализовать возможность добавления новых ЖР.
Реализовать функционал добавления ЖР к шагам и задачам, путем добавления в отображения полей с ЖР.
У шагов может быть несколько ЖР. Реализовать промежуточную таблицу связей между шагом и ЖР.
У задач может быть несколько ЖР. Реализовать промежуточную таблицу связей между задачей и ЖР.
(таблица ЖР есть на гугл [диске)](https://drive.google.com/file/d/1px7M4z02DN_q0q5CsUWCg3smdkNAqQYI/view?usp=sharing)

**Мотивация:**

Заказчик хочет оценивать шаги и задачи при помощи ЖР для своих внутренних целей. 

**Критерии приемки:**

При детальном просмотре шага или задачи под администратором, должна быть кнопка "Добавить Желаемый результат".
При нажатии на кнопку, должно открыться окно, в котором можно добавить несколько ЖР к шагу или задаче., либо шагов, должны отображаться ЖР, если они добавлены.
После, нажав на кнопку сохранить, в БД должны быть записаны связи между шагом/задачей и ЖР. При просмотре задач

**Планируемое время работы:**
8 часов

**Comment by GalinaDugina** [comment]
тикет закончен, затрачено 6 часов
