### ISSUE TITLE
Исправление ошибок создания пользователя

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#73]
**Конечный результат:**

Пользователь создается, при неверном вводе данных выводятся ошибка валидации
1. Если данное имя существует
2. Если пароли не совпадают
3. Если пароль создается не в соответствии с требованиями
4. Если не указанны поля: имя, фамилия, почтовый адрес, не выбрана задача

**План решения:**

Добавить валидацию для модели регистрации пользователя
Добавить "span" поля для вывода ошибок о валидации
После успешного создания пользователя, добавить переадресацию на список пользователей
Исправить ошибку в label "Уровень доступа"

**Мотивация:**

Необходимо доработать работу с пользователями чтобы к ним не возвращаться

**Критерии приемки:**

При создании пользователя с пропущенными полями, при неправильно указанном пароле,
при неуказанной задачи пользователя пользователь не создается и выводятся уведомления об ошибке

**Планируемое время работы:**
2 часа

**Comment by GalinaDugina** [comment]
2 часа
