### ISSUE TITLE
Исправить ошибки добавления Вопрос-Ответов

### ISSUE THREAD

**Issue by GlebChuprin** [CSharp2-3Command2/Guide#75]
Конечный результат:

Сущность вопрос-ответов добавляется, все работает исправно

План решения:

1. Проанализировать проблему возникновения ошибки
2. Исправить ее

Мотивация:

На собеседовании с заказчиком при наполнении базы возникали ошибки создания сущностей под них попали вопрос-ответы, сейчас нужно исправить ошибки для дальнейшей сборки бизнес процессов

Критерии приемки:

Вопрос-ответ создается, все работает исправно

Планируемое время работы:
30мин

**Comment by GalinaDugina** [comment]
30 минут потрачено
