### ISSUE TITLE
Реализовать возможность Редактирования Задачи

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#76]
**Мотивация:** 
При переходе из Списка Задач к конкретной Задаче администратору надо иметь возможность редактировать задачу, шаги и ЖР входящие в нее
**План решения:** 
В данный момент при переходе на редактирование Задачи списки Шагов и ЖР выходят с кнопкой «корзина» -  надо реализовать удаление связи между Задачей и Шагом, Задачей и ЖР по нажатию на «корзину». Обязательно с вопросом удалять или нет.
 Добавление новых  реализовать путем перехода на страницу добавления Шагов или ЖР .

**Критерии приемки:**
При просмотре Списка Задач при нажатии на "карандаш" открывается страница редактирования Задачи.
На ней Название и Содержание Задачи, так же списки Шагов и ЖР,
На этой же странице можно удалять связь Задачи с Шагом или  ЖР
А чтобы добавить Шаг или ЖР надо перейти на другие страницы добавления( надо продумать как это лучше делать, сейчас как то запутанно)

**Планируемое время работы:**
3 часа

**Comment by AlexeyGoikolov** [comment]
Затраченное время 4 часа. Были проблемы работы JS с формой
