### ISSUE TITLE
Библиотека. Сделать совместный просмотр Книг и Источников в одном списке

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#78]
**Мотивация:**
Заказчик хочет всю подобную информацию видеть в одном месте
**План решения:**
В одном списке не получится (так как поля не совпадают)
Поэтому сделать переход на страницу через пункт "Библиотека"
На странице сделать два портлета(с функциями открывания-закрывания) :Книги и Прочее
При открытии : Таблица с данными
Сделать Аналогично на стороне Пользователя
**Критерии приемки:**
Заходим во вкладку Библиотека и видем два портлета Книги и Иное
Портлет можно открыть и просмотреть содержимое в виде таблицы с сортировкой и поиском
**Планируемое время работы:**
2ч

**Comment by MuhtarLotov** [comment]
потрачено 2ч
