### ISSUE TITLE
Добавить админу возможность регистрации пользователей

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#8]
**Конечный результат:**

Добавление пользователю с ролью "admin" функционала регистрации пользователей

**План решения:**

Описать экшен регистрации пользователя с правами доступа только для администратора.
Добавить форму регистрации пользователя. Добавить в личном кабинете администратора кнопку для регистрации новых пользователей.

**Мотивация:**

Права доступа к контенту в проекте должны предоставляться администратором только для сотрудников. 

**Критерии приемки:**

После входа администратора, должен открыться личный кабинет с кнопкой добавления нового пользователя. При нажатии на кнопку "добавить пользователя", открывается форма для регистрации нового пользователя. После внесения данных в форму и нажатия кнопки "зарегистрировать", новый пользователь с ролью "user" должен отобразиться в БД.
В дальнейшем пользователь без проблем должен залогиниться по Логину и паролю, которые были указаны администратором при регистрации.

**Планируемое время работы:**
30-45 мин

**Comment by GlebChuprin** [comment]
Предполагаемое время: 30-45 мин
Время по факту: 25 мин
