### ISSUE TITLE
Убрать обязательные к заполнению поля

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#80]
**План решения:**
в Моделях , кроме User и связанных с ним моделях, убрать поля обязательные к заполнению и убрать “красную звездочку” на представлениях возле обязательных полей

**Мотивация:**
Просьба Заказчика :  В принципе поля обязательные для заполнения должны оговариваться с Заказчиком. Это ведь выставляемое системой ограничение, но на каком основании?)) Уберите все ограничения. Лучше оставить возможность добавить ограничение позже нашим администратором, когда мы поймем, что именно должно жестко регулироваться к заполнению
**Критерии приемки:**
В проекте все сущности создаются без обязательных полей
**Планируемое время работы:**
1 час

**Comment by AlexeyGoikolov** [comment]
Затраченное время 1 час
