### ISSUE TITLE
 Убрать слово "сокращенно" при просмотре Термина

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#81]
**План решения:**
В представлении для просмотра термина на стороне админа и на стороне пользователя убрать вывод слова "сокращенно", оставить только скобки
**Мотивация:**
Просьба Заказчика :  Сокращенно - это наверное место для аббревиатуры? Но если аббревиатуры у термина нет, то значит ее просто нет.

**Критерии приемки:**
На представлении если есть аббревиатура у термина она выводится в скобках, если нет ничего не выводится
**Планируемое время работы:**
15 минут

**Comment by AlexeyGoikolov** [comment]
Затраченное время 20 минут. Подправил представление на стороне пользователя
