### ISSUE TITLE
Убрать слово "Название" при добавлении Шагов и Задач

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#82]
**План решения:**
Убрать на представлении исользование этого слова
**Мотивация:**
спользование слова Название смущает пользователя и не несет особенного смысла

**Критерии приемки:**
Список Шагов, как и Список Задач выводятся при добавлении без указателя "Название"
**Планируемое время работы:**
15м

**Comment by MuhtarLotov** [comment]
затраченное время 15м
