### ISSUE TITLE
Проверка работы функционала Комментарии

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#84]
**План решения:**

Просмотреть представления проекта где исользованы Комментарии, проверить их работу
Проверить работу Комментариев в Шагах
Если не работают поправить код
Провести проверку как у User так и у Admin

**Мотивация:**
На некоторых представлениях Комментарии не отображаются
**Критерии приемки:**
В проекте на всех страницах, где добавлен комментарий все работает
**Планируемое время работы:**
3 часа

**Comment by AlexeyGoikolov** [comment]
Затраченное время 3 часа
