### ISSUE TITLE
Откорректировать переход на просмотр на стороне пользователя

### ISSUE THREAD

**Issue by GalinaDugina** [CSharp2-3Command2/Guide#86]
**План решения:**
Просмотреть код программы и устранить ошибки:
 1./admin/IssuesManage/Index не работает переход на просмотр со стороны пользователя
2./admin/StepsManage/Index не работает переход на просмотр со стороны пользователя
3. /admin/GlossarysManage/Index переход на вид пользователя не происходит

**Мотивация:**
Откорректировать работу программы, устранить недочеты в работе
**Критерии приемки:**
Указанные ошибки устранене, программа работает без сбоев
**Планируемое время работы:**

**Comment by MuhtarLotov** [comment]
Затраченное время 20м
