### ISSUE TITLE
Исправить сохранения Задачи и Шага

### ISSUE THREAD

**Issue by MuhtarLotov** [CSharp2-3Command2/Guide#88]
**План решения:**
Создание Задача
При нажатий создать должно сохраниться и открыться список задачи 
Создание Шага
При нажатий создать должно сохраниться и открыться список шагов
**Мотивация:**
при нажатии создать открывается создания ЖР и возникает недопонимания о создании задачи или шага 
**Критерии приемки:**
Создание Задача
При нажатий создать должно сохраниться и открыться список задачи 
Создание Шага
При нажатий создать должно сохраниться и открыться список шагов
**Планируемое время работы:**
1,5 часа

**Comment by GalinaDugina** [comment]
ушло 1,5 часа, так как обнаружилась ошибка в программе, только после ее исправления смогла приступить  к работе
