### ISSUE TITLE
Реализовать список должностей с назначенными задачами 

### ISSUE THREAD

**Issue by MuhtarLotov** [CSharp2-3Command2/Guide#89]
**План решения:**
Нужно сделать к "задачи к должностям" список назначенных задач

**Мотивация:**
Должна быть возможность просмотреть назначенные задачи 

**Критерии приемки:**
при открытии страницы будут выводиться список должностей с их назначенными задачами 

**Планируемое время работы:**
2часа

**Comment by GalinaDugina** [comment]
потрачено 2 часа, дополнительно сделала редактирование: удаление связи Задача-Должность
