### ISSUE TITLE
Добавить функционал отключения(удаления) пользователя

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#9]
**Конечный результат:**

Добавление возможности отключения пользователя администратором

**План решения:**

В личном кабинете администратора добавить кнопку "Удалить пользователя".
Добавить для модели User свойство Active(boolean) по умолчанию true.
Написать метод в контроллере, который будет менять свойство с true на false.
Предусмотреть поиск пользователя по логину.
Предусмотреть предварительное подтверждение удаления пользователя, путем вопроса "Вы действительно хотите удалить пользователя?" и ответами "Да" и  "Нет"

Предусмотреть возможность залогиниться только пользователям у которых свойство Active = true. В случае false, пользователь не должен аутентифицироваться.

**Мотивация:**

Администратор должен иметь возможность "удалять"(отключать) пользователей, чтобы закрыть доступы к данным в проекте.

**Критерии приемки:**

В личном кабинете администратора, при нажатии на кнопку "Удалить пользователя", откроется окно, в котором необходимо будет в поле поиска внести логин, после чего нажать кнопку "Удалить". После нажатия кнопки "Удалить", последует вопрос "Вы действительно хотите удалить пользователя?" и ответами "Да" и  "Нет". При нажатии да, у пользователя должно поменяться свойство Active с true на false и соответственно должен быть закрыт доступ к аутентификации.

**Планируемое время работы:**
15-25 мин

**Comment by GalinaDugina** [comment]
не реализовано : Предусмотреть предварительное подтверждение удаления пользователя, путем вопроса "Вы действительно хотите удалить пользователя?" и ответами "Да" и "Нет"
не проходит по критериям приемки
