### ISSUE TITLE
Возможность добавить дополнительный язык к глоссариям 

### ISSUE THREAD

**Issue by MuhtarLotov** [CSharp2-3Command2/Guide#90]
**План решения:**
добавить в создании глоссариям поля выбора языка
добавить кнопку в просмотре глоссария добавить новый язык, по нажатии открывать добавления глоссария с переданным id первоисточника 
при сохраненный проверять все связи первоисточника и добавлять связь со всеми связами первоисточника и с ним 

**Мотивация:**
Должна быть возможность добавить к глоссариям двуязычия и боле чтобы было переводы на другом языке    

**Критерии приемки:**
при добавления нового языка к глоссарию должно создаваться связь с первоисточником и совсем другими языкам что были добавлен до него  

**Планируемое время работы:**
4 часа

**Comment by GalinaDugina** [comment]
потрачено 4,5 часа, так как пришлось дополнительно исправлять удаление
