### ISSUE TITLE
Добавить кнопку редактирования в шагах

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#92]
**Конечный результат:**

Наличие действующей кнопки "Редактировать" при просмотре шага

**План решения:**

Добавить в представление Details в шагах кнопку "Редактировать" с переходом к редактированию шага.

**Мотивация:**

При просмотре шага должна быть возможность перейти к редактированию не выходя из шага.

**Критерии приемки:**

При просмотре задачи администратором, справа сверху присутствует кнопка "Редактировать", нажав на которую откроется форма для редактирования шага.

**Планируемое время работы:**
30 минут

**Comment by GalinaDugina** [comment]
потрачено 30 мин, дополнительно сделала отображение вверху страницы откуда произошел переход на редактирование
