### ISSUE TITLE
Вывод БП рядом с назначенными к должности задачами

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#95]
**Конечный результат:**

При просмотре назначенных к должности задач, отображается название Бизнес процесса, к которому относится данная задача. У пользователя добавить возможность сортировки задач по Бизнес процессу.

**План решения:**

Поменять логику в контроллере и представление у административной и публичной части. Добавить отображение Бизнес процесса у назначенной к должности задаче. Добавить таблицу для поиска и фильтрации Задач по Бизнес процессу.

**Мотивация:**

Для поиска и более удобного изучения задач, пользователь должен иметь возможность понимать к какому БП относится та или иная задача

**Критерии приемки:**

При просмотре назначенных к должности задач, отображается таблица с названием Задачи и возле отображается название бизнес процесса, к которому эта задача относится. При вводе в поле поиска, задачи должны фильтроваться по бизнес процессам.

**Планируемое время работы:**
1,5 часа

**Comment by GalinaDugina** [comment]
время 1.5 часа. Дополнительно сделала контроллер и детальный просмотр для БП на стороне пользователя
