### ISSUE TITLE
Добавление новой сущности Автор, промежуточной таблицы и удаление автора из сущности Книга

### ISSUE THREAD

**Issue by AlexeyGoikolov** [CSharp2-3Command2/Guide#96]
**Конечный результат:**

Удаленное поле "Автор" из сущности "Книга" и добавленная новая сущность "Автор". Добавление новой связывающей таблицы Книга-Автор.

**План решения:**

Из сущности "Book" убрать поле автор. Добавить 2 новые сущности "Author" и "BookAuthor". В сущности Author должны быть поля Id и Name. В связывающей сущности, должны быть поля с вторичными ключами(FK) для сущностей "Book" и "Author". 
В форме добавления книги, добавить логику присвоения связи Книга-Автор через новую сущность.

**Мотивация:**

У книг может быть несколько авторов и для заполнения автора у книги, необходимо предусмотреть возможность добавления нескольких авторов

**Критерии приемки:**

При добавлении новой книги, в поле автор заполняется автор и данное поле добавляется в сущность "Author". Между книгой и автором создается связь в промежуточной таблице.
При выводе автора в представлениях, имя автора тянется из таблицы "Author" через связующую таблицу.

**Планируемое время работы:**
2ч

**Comment by MuhtarLotov** [comment]
потрачено 2ч
